name: Deploy HTML Website to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install HTML Validator
        run: |
          npm install -g html-validate

      - name: Validate HTML
        run: |
          html-validate "**/*.html"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
